# --- 1. Despliegue (Deployment) para orders-service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          #image: tunombredeusuario/plataforma-orders-service:latest # <-- Imagen para el servicio de órdenes
          image: plataforma-orders-service:latest # <-- Nombre local
          imagePullPolicy: Never               # <-- Añadir esta línea
          ports:
            - containerPort: 3002 # <-- Puerto del contenedor de órdenes
          livenessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          env: # Asumo que usa las mismas variables de entorno y secretos
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: retail-platform-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: retail-platform-config
                  key: DB_PORT
            - name: DB_DATABASE
              value: "plataforma_retail_orders"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret

---
# --- 2. Servicio (Service) para orders-service ---
apiVersion: v1
kind: Service
metadata:
  name: orders-service # Este es el nombre DNS (ej. http://orders-service)
spec:
  type: LoadBalancer 
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 3002       # Puerto público
      targetPort: 3002 # <-- Puerto del contenedor de órdenes