# --- 1. Despliegue (Deployment) para reports-service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reports-service
  template:
    metadata:
      labels:
        app: reports-service
    spec:
      containers:
        - name: reports-service
          #image: tunombredeusuario/plataforma-reports-service:latest # <-- Imagen para el servicio de reportes
          image: plataforma-reports-service:latest # <-- Nombre local
          imagePullPolicy: Never               # <-- Añadir esta línea
          ports:
            - containerPort: 3005 # <-- Puerto del contenedor de reportes
          livenessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            # --- URLs de Microservicios para Reportes ---
            - name: ORDERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: retail-platform-config
                  key: ORDERS_SERVICE_URL
            - name: INVENTORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: retail-platform-config
                  key: INVENTORY_SERVICE_URL
            - name: SUPPLIERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: retail-platform-config
                  key: SUPPLIERS_SERVICE_URL
            - name: STORE_OPS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: retail-platform-config
                  key: STORE_OPS_SERVICE_URL
            
            # --- Secreto de JWT ---
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
---
# --- 2. Servicio (Service) para reports-service ---
apiVersion: v1
kind: Service
metadata:
  name: reports-service # Este es el nombre DNS (ej. http://reports-service)
spec:
  type: LoadBalancer 
  selector:
    app: reports-service
  ports:
    - protocol: TCP
      port: 3005       # Puerto público
      targetPort: 3005 # <-- Puerto del contenedor de reportes